import { Component, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SettingsService } from '../../core/services/settings.service';

@Component({
  selector: 'app-variation-config',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="variation-config">
      <div class="section-intro">
        <h3>Generation Preferences</h3>
        <p>Customize how many variations AI generates</p>
      </div>

      <div class="config-cards">
        <div class="config-card">
          <div class="config-header">
            <div class="config-label">Default variations</div>
            <div class="config-value">{{ defaultCount() }}</div>
          </div>
          <div class="slider-container">
            <input
              type="range"
              class="slider"
              [min]="1"
              [max]="maxCount()"
              [ngModel]="defaultCount()"
              (ngModelChange)="setDefaultCount($event)"
            />
            <div class="slider-track">
              <div class="slider-fill" [style.width.%]="defaultPercent()"></div>
            </div>
          </div>
          <p class="config-hint">Number of variations generated by default</p>
        </div>

        <div class="config-card">
          <div class="config-header">
            <div class="config-label">Maximum variations</div>
            <div class="config-value">{{ maxCount() }}</div>
          </div>
          <div class="slider-container">
            <input
              type="range"
              class="slider"
              [min]="1"
              [max]="20"
              [ngModel]="maxCount()"
              (ngModelChange)="setMaxCount($event)"
            />
            <div class="slider-track">
              <div class="slider-fill" [style.width.%]="maxPercent()"></div>
            </div>
          </div>
          <p class="config-hint">Upper limit for the variation slider</p>
        </div>
      </div>

      <div class="reset-section">
        <button class="reset-btn" (click)="resetToDefaults()">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <polyline points="1 4 1 10 7 10"/>
            <path d="M3.51 15a9 9 0 102.13-9.36L1 10"/>
          </svg>
          Reset to Defaults
        </button>
      </div>
    </div>
  `,
  styles: [`
    .variation-config {
      display: flex;
      flex-direction: column;
      gap: 1.5rem;
    }

    .section-intro h3 {
      font-family: var(--font-display);
      font-size: 1.125rem;
      font-weight: 600;
      color: var(--text-bright);
      margin: 0 0 0.375rem;
    }

    .section-intro p {
      font-size: 0.875rem;
      color: var(--text-muted);
      margin: 0;
    }

    .config-cards {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }

    .config-card {
      padding: 1.25rem;
      background: var(--parchment-mid);
      border: 1px solid var(--border-subtle);
      border-radius: var(--radius-lg);
    }

    .config-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 1rem;
    }

    .config-label {
      font-size: 0.9375rem;
      font-weight: 600;
      color: var(--text-primary);
    }

    .config-value {
      font-family: var(--font-display);
      font-size: 1.5rem;
      font-weight: 700;
      color: var(--amber);
    }

    .slider-container {
      position: relative;
      height: 8px;
      margin-bottom: 0.75rem;
    }

    .slider {
      position: absolute;
      width: 100%;
      height: 100%;
      opacity: 0;
      cursor: pointer;
      z-index: 2;
    }

    .slider-track {
      position: absolute;
      inset: 0;
      background: var(--parchment-light);
      border-radius: var(--radius-full);
      overflow: hidden;
    }

    .slider-fill {
      height: 100%;
      background: linear-gradient(90deg, var(--amber-deep), var(--amber));
      border-radius: var(--radius-full);
      transition: width var(--transition-fast);
    }

    .config-hint {
      font-size: 0.75rem;
      color: var(--text-muted);
      margin: 0;
    }

    .reset-section {
      padding-top: 0.5rem;
    }

    .reset-btn {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.75rem 1rem;
      background: transparent;
      border: 1px solid var(--border-subtle);
      border-radius: var(--radius-md);
      color: var(--text-secondary);
      font-size: 0.875rem;
      font-weight: 500;
      cursor: pointer;
      transition: all var(--transition-fast);
    }

    .reset-btn svg {
      width: 16px;
      height: 16px;
    }

    .reset-btn:hover {
      background: var(--parchment-mid);
      border-color: var(--border-visible);
      color: var(--text-primary);
    }
  `],
})
export class VariationConfigComponent {
  constructor(private settingsService: SettingsService) {}

  defaultCount = computed(() => this.settingsService.defaultVariationCount());
  maxCount = computed(() => this.settingsService.maxVariationCount());

  defaultPercent = computed(() => {
    return (this.defaultCount() / this.maxCount()) * 100;
  });

  maxPercent = computed(() => {
    return (this.maxCount() / 20) * 100;
  });

  setDefaultCount(count: number): void {
    this.settingsService.setVariationCount(count);
  }

  setMaxCount(max: number): void {
    this.settingsService.setMaxVariationCount(max);
  }

  resetToDefaults(): void {
    this.settingsService.resetToDefaults();
  }
}
